name: Production pipeline

on:
  workflow_dispatch:  # Allows manual execution

jobs:
   build-and-deploy:
       runs-on: ubuntu-latest
       steps:
       - name: 'Checkout GitHub Action'
         uses: actions/checkout@main

       - name: 'Login via Azure CLI'
         uses: azure/login@v1
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}

       - name: 'Set up Kubernetes'
         uses: azure/aks-set-context@v2
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
           cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
           resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}

       - name: 'Build and push image'
         uses: azure/docker-login@v1
         with:
           login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
           username: ${{ secrets.REGISTRY_USERNAME }}
           password: ${{ secrets.REGISTRY_PASSWORD }}
       - run: |
           cp swagger.prod .env
           docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/whatnowapi:${{ github.sha }} -f ./docker/Dockerfile .
           docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/whatnowapi:${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/whatnowapi:latest

           docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/whatnowapi:${{ github.sha }}
           docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/whatnowapi:latest
       - name: 'Copy production values files'
         run: |
           cp ./helm-chart/values-production.yaml ./helm-chart/values.yaml

       - name: 'Deploy to AKS with Helm'
         run: |
           helm upgrade --install whatnow ./helm-chart \
             --namespace ${{ secrets.AKS_CLUSTER_NAMESPACE }} \
             --create-namespace


